class SeedDb < ActiveRecord::Migration[6.1]
  def up
    Rails.logger.level = Logger::DEBUG
    execute <<-SQL

INSERT INTO public.warehouse (id, name, location) VALUES (1, 'Factory Warehouse', 'FACTORY');
INSERT INTO public.warehouse (id, name, location) VALUES (2, 'Store Warehouse', 'STORE');
INSERT INTO public.warehouse (id, name, location) VALUES (3, 'Faulty Warehouse', 'FAULTY');

INSERT INTO public.component (id, category, name, description, price_cost) VALUES (1, 'COMPUTER', 'KITT', 'On-board computer', '$ 750,50');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (2, 'COMPUTER', 'J.A.R.V.I.S', 'On-board computer', '$ 880,50');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (3, 'COMPUTER', 'Icarus', 'On-board computer', '$ 625,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (4, 'COMPUTER', 'GBLX 1000', 'On-board computer', '$ 350,50');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (5, 'COMPUTER', 'SAL-9000', 'On-board computer', '$ 450,50');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (6, 'COMPUTER', 'HAL-9000', 'On-board computer', '$ 750,50');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (7, 'WHEEL', 'Luxury Wheel', 'Wheel', '$ 88,45');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (8, 'WHEEL', 'Regular Wheel', 'Wheel', '$ 40,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (9, 'LASER', 'Phaser', 'Laser', '$ 30,95');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (10, 'LASER', 'Blaster', 'Laser', '$ 25,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (11, 'LASER', 'Proton pack', 'Laser', '$ 55,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (12, 'CHASSIS', 'Antigualla Blindada', 'Chassis Component', '$ 150,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (13, 'CHASSIS', 'Compact Pussycat', 'Chassis Component', '$ 155,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (14, 'CHASSIS', 'Superheterodino', 'Chassis Component', '$ 166,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (15, 'CHASSIS', 'Alambique Veloz', 'Chassis Component', '$ 155,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (16, 'CHASSIS', 'Rocomóvil', 'Chassis Component', '$ 178,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (17, 'CHASSIS', 'Troncoswagen', 'Chassis Component', '$ 185,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (18, 'CHASSIS', 'Stuka Rakuda', 'Chassis Component', '$ 123,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (19, 'CHASSIS', 'Espantomóvil', 'Chassis Component', '$ 198,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (20, 'CHASSIS', 'Auto-Convertible', 'Chassis Component', '$ 135,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (21, 'CHASSIS', 'Súper Chatarra Special', 'Chassis Component', '$ 144,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (22, 'CHASSIS', 'Súper Perrari', 'Chassis Component', '$ 123,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (23, 'ENGINE', 'Hyperdrive', 'Engine Component', '$ 323,80');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (24, 'ENGINE', 'Warp Core', 'Engine Component', '$ 383,70');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (25, 'ENGINE', 'Epstein Drive', 'Engine Component', '$ 255,20');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (26, 'SEAT', 'Super Comfort Seat', 'Seat Component', '$ 120,75');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (27, 'SEAT', 'Regular Comfort Seat', 'Seat Component', '$ 64,75');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (28, 'PAINT', 'Paint', 'Paint', '$ 64,75');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (29, 'BASIC_ASSEMBLY', 'Basic structure Assy', 'Robot Basic Assembly', '$ 4,75');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (30, 'ELECTRONIC_ASSEMBLY', 'Electronic devices Assy', 'Robot Electronics', '$ 5,20');
INSERT INTO public.component (id, category, name, description, price_cost) VALUES (31, 'FINAL_ASSEMBLY', 'Painting and Finals Assy', 'Robot Painter', '$ 7,25');


INSERT INTO public.model (id, name, revenue_factor) VALUES (1, 'Antigualla Blindada', 0.50);
INSERT INTO public.model (id, name, revenue_factor) VALUES (2, 'Compact Pussycat', 0.70);
INSERT INTO public.model (id, name, revenue_factor) VALUES (3, 'Superheterodino', 0.50);
INSERT INTO public.model (id, name, revenue_factor) VALUES (4, 'Alambique Veloz', 0.50);
INSERT INTO public.model (id, name, revenue_factor) VALUES (5, 'Rocomóvil', 0.30);
INSERT INTO public.model (id, name, revenue_factor) VALUES (6, 'Troncoswagen', 0.50);
INSERT INTO public.model (id, name, revenue_factor) VALUES (7, 'Stuka Rakuda', 0.50);
INSERT INTO public.model (id, name, revenue_factor) VALUES (8, 'Espantomóvil', 0.40);
INSERT INTO public.model (id, name, revenue_factor) VALUES (9, 'Auto-Convertible', 0.50);
INSERT INTO public.model (id, name, revenue_factor) VALUES (10, 'Súper Chatarra Special', 0.40);
INSERT INTO public.model (id, name, revenue_factor) VALUES (11, 'Súper Perrari', 0.40);


INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (12, 1, 12, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (13, 2, 13, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (14, 3, 14, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (15, 4, 15, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (16, 5, 16, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (17, 6, 17, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (18, 7, 18, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (19, 8, 19, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (20, 9, 20, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (21, 10, 21, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (22, 11, 22, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (23, 1, 23, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (24, 2, 24, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (25, 3, 25, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (26, 4, 23, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (27, 5, 24, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (28, 6, 25, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (29, 7, 23, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (30, 8, 24, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (31, 9, 25, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (32, 10, 23, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (33, 11, 24, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (34, 1, 1, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (35, 2, 2, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (36, 3, 3, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (37, 4, 4, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (38, 5, 5, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (39, 6, 6, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (40, 7, 1, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (41, 8, 2, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (42, 9, 3, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (43, 10, 4, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (44, 11, 5, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (45, 1, 9, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (46, 2, 10, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (47, 3, 11, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (48, 4, 9, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (49, 5, 10, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (50, 6, 11, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (51, 7, 9, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (52, 8, 10, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (53, 9, 11, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (54, 10, 9, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (55, 11, 10, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (56, 1, 7, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (57, 2, 8, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (58, 3, 7, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (59, 4, 8, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (60, 5, 7, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (61, 6, 8, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (62, 7, 7, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (63, 8, 8, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (64, 9, 7, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (65, 10, 8, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (66, 11, 7, 4);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (67, 1, 26, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (68, 2, 27, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (69, 3, 26, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (70, 4, 27, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (71, 5, 26, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (72, 6, 27, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (73, 7, 26, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (74, 8, 27, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (75, 9, 26, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (76, 10, 27, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (77, 11, 26, 2);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (78, 1, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (79, 2, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (80, 3, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (81, 4, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (82, 5, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (83, 6, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (84, 7, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (85, 8, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (86, 9, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (87, 10, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (88, 11, 28, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (89, 1, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (90, 2, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (91, 3, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (92, 4, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (93, 5, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (94, 6, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (95, 7, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (96, 8, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (97, 9, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (98, 10, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (99, 11, 29, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (101, 1, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (102, 2, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (103, 3, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (104, 4, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (105, 5, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (106, 6, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (107, 7, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (108, 8, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (109, 9, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (110, 10, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (111, 11, 30, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (112, 1, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (113, 2, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (114, 3, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (115, 4, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (116, 5, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (117, 6, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (118, 7, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (119, 8, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (120, 9, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (121, 10, 31, 1);
INSERT INTO public.model_specification (id, model_id, component_id, qty) VALUES (122, 11, 31, 1);


    SQL
  end
end
